name: Setup Dependencies
description: ""

inputs:
  os:
    description: Operating System
    required: false
    default: "linux"
  cache-id:
    description: Cache ID
    required: true

runs:
  using: composite
  steps:
    - name: Get LLVM Version from Rust
      shell: bash
      run: |
        rustc --version --verbose | sed -n 's/LLVM version: \([0-9]\{1,\}\).*/LLVM_MAJOR_VERSION=\1/p' >> $GITHUB_ENV
        rustc --version --verbose | sed -n 's/LLVM version: \([0-9]\{1,\}\.[0-9]\{1,\}\.[0-9]\{1,\}\)/LLVM_VERSION=\1/p' >> $GITHUB_ENV

    - name: Install Dependencies on Windows
      if: inputs.os == 'windows'
      env:
        MOZTOOLS_LINK: https://github.com/servo/servo-build-deps/releases/download/msvc-deps
        MOZTOOLS_VERSION: "4.0"
        MOZTOOLS_PATH: ${{ github.workspace }}\\target\\dependencies\\moztools-4.0
      shell: pwsh
      run: |
        curl -fsSL "$env:MOZTOOLS_LINK/moztools-$env:MOZTOOLS_VERSION.zip" --create-dirs -o target/dependencies/moztools.zip
        cd target/dependencies && unzip -qo moztools.zip -d .
        Write-Output "MOZTOOLS_PATH=$env:MOZTOOLS_PATH" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

        Invoke-RestMethod -Uri https://get.scoop.sh | Invoke-Expression
        scoop install "llvm@$env:LLVM_VERSION" --global
        $(
          Write-Output "$env:PROGRAMDATA\scoop\shims"
          Get-Content "$env:GITHUB_PATH"
        ) | Set-Content -Path "$env:GITHUB_PATH" -Encoding utf8

        Write-Output "CC=clang-cl" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
        Write-Output "CXX=clang-cl" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
        Write-Output "AR=llvm-lib" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
        Write-Output "LINKER=lld-link" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

        Write-Output "CCACHE=sccache" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

    - name: Install Dependencies on MacOS
      if: inputs.os == 'macos'
      shell: bash
      run: |
        brew list -1 | grep python | while read formula; do brew unlink $formula; brew link --overwrite $formula; done
        brew install llvm@$LLVM_MAJOR_VERSION yasm
        { echo "$(brew --prefix llvm@$LLVM_MAJOR_VERSION)/bin"; cat "$GITHUB_PATH"; } > "$GITHUB_PATH.new"
        mv "$GITHUB_PATH.new" "$GITHUB_PATH"

        echo "CC=clang" >> $GITHUB_ENV
        echo "CXX=clang++" >> $GITHUB_ENV
        echo "AR=llvm-ar" >> $GITHUB_ENV

        echo "CCACHE=sccache" >> $GITHUB_ENV
        echo "RUSTC_WRAPPER=sccache" >> $GITHUB_ENV

    - name: Install Dependencies on Linux
      if: inputs.os == 'linux'
      shell: bash
      run: |
        curl -fsSL https://apt.llvm.org/llvm.sh -o llvm.sh && chmod +x llvm.sh
        sudo env DPKG_FORCE=overwrite ./llvm.sh "$LLVM_MAJOR_VERSION" all
        { echo "/usr/lib/llvm-$LLVM_MAJOR_VERSION/bin"; cat "$GITHUB_PATH"; } > "$GITHUB_PATH.new"
        mv "$GITHUB_PATH.new" "$GITHUB_PATH"

        echo "CC=clang" >> $GITHUB_ENV
        echo "CXX=clang++" >> $GITHUB_ENV
        echo "AR=llvm-ar" >> $GITHUB_ENV

        echo "CCACHE=sccache" >> $GITHUB_ENV
        echo "RUSTC_WRAPPER=sccache" >> $GITHUB_ENV

    - name: Install Just
      uses: taiki-e/install-action@just

    - name: Install Nextest
      uses: taiki-e/install-action@nextest

    - name: Setup sccache
      uses: mozilla-actions/sccache-action@v0.0.7

    - name: Cache Cargo Cache and Git Database
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
        key: cargo-${{ inputs.cache-id }}-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: cargo-${{ inputs.cache-id }}-
